version: '3.8'


services:
  db:
    image: postgres:15.1-alpine
    restart: on-failure
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -U postgres" ]
      interval: 5s
      timeout: 20s
      retries: 100
    networks:
      custom:

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    container_name: aiohttp-app
    restart: on-failure
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

    networks:
      custom:


networks:
  custom: