version: '3.8'


services:
  db:
    image: postgres:15.1-alpine
    restart: on-failure
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 20s
      retries: 100
    networks:
      custom:

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    container_name: fastapi-app
    restart: on-failure
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy


networks:
  custom: